name: "SMA Energy Meter emulator"
description: "Simulate one or more SMA energy meters based on mqtt messages."
version: "rc-0.0.11"
slug: sma
url: "https://github.com/Roeland54/SMA-Energy-Meter-emulator"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
services:
  - "mqtt:need"
options:
  enable_mqtt: true
  mqtt:
    broker: "auto_broker"
    port: "auto_port"
    username: "auto_user"
    password: "auto_password"
schema:
  enable_mqtt: bool?
  mqtt:
    broker: str
    port: str?
    username: str?
    password: str?
  enable_homewizard: bool?
  homewizard_manual_addresses:
    - match(^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$)?
  homewizard_destination_addresses:
    - match(^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$)?
  debug_logging: bool?
  disable_logging: bool?
image: "ghcr.io/roeland54/{arch}-sma-energy-meter-emulator"
